services:
  db:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_search
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - image-search-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
    - uploaded_images:/app/uploaded_images
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/image_search
      - BASE_URL=https://api-digitalizacion-de-imagenes-test.ater.gob.ar
      - ALLOWED_ORIGINS=https://digitalizacion-de-imagenes-test.ater.gob.ar
      - SIMILARITY_THRESHOLD=0.5
    depends_on:
      - db
    networks:
      - image-search-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api-digitalizacion-de-imagenes-test.ater.gob.ar
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=https://api-digitalizacion-de-imagenes-test.ater.gob.ar
    depends_on:
      - backend
    networks:
      - image-search-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/server.crt:/etc/ssl/certs/server.crt
      - ./ssl/server.key:/etc/ssl/certs/server.key
    depends_on:
      - frontend
      - backend
    networks:
      - image-search-network
  
  aprendiendo-react:
    build:
      context: /home/mongodb/aprendiendo-react/current
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - /home/mongodb/aprendiendo-react/current/.env.local

networks:
  image-search-network:
    driver: bridge

volumes:
  pgdata:
  uploaded_images:
